[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rec_platform = "9YgyLsBaGy8mU4X4k4CuPmcxhwkAcRD51mGvjWXkeMqn"

[programs.devnet]
rec_platform = "9YgyLsBaGy8mU4X4k4CuPmcxhwkAcRD51mGvjWXkeMqn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/pvionis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
